// Code generated by moo. DO NOT EDIT.

package e2e

import (
	"fmt"
	"net/mail"
	"strings"
)

// ---- Point ----

// PointOption configures a Point.
type PointOption func(*Point)

// WithX sets the X field.
func WithX(v int) PointOption {
	return func(x *Point) { x.X = v }
}

// WithY sets the Y field.
func WithY(v int) PointOption {
	return func(x *Point) { x.Y = v }
}

// WithName sets the Name field.
func WithName(v string) PointOption {
	return func(x *Point) { x.Name = v }
}

// WithEmail sets the Email field.
func WithEmail(v string) PointOption {
	return func(x *Point) { x.Email = v }
}

// WithKind sets the Kind field.
func WithKind(v string) PointOption {
	return func(x *Point) { x.Kind = v }
}

// WithTags sets the Tags field.
func WithTags(v []string) PointOption {
	return func(x *Point) { x.Tags = v }
}

// NewPoint constructs a Point with defaults applied, then options,
// then validates the result.
func NewPoint(opts ...PointOption) (*Point, error) {
	x := &Point{
		X:    0,
		Y:    0,
		Name: "origin",
	}
	for _, opt := range opts {
		opt(x)
	}
	if err := x.Validate(); err != nil {
		return nil, err
	}
	return x, nil
}

// Validate checks the invariants declared by `moo:` tags on Point.
func (x *Point) Validate() error {
	if x.Y == 0 {
		return fmt.Errorf("Y is required")
	}
	if len(x.Name) < 1 {
		return fmt.Errorf("Name length must be >= 1")
	}
	if len(x.Name) > 64 {
		return fmt.Errorf("Name length must be <= 64")
	}
	if x.Email != "" {
		if _, err := mail.ParseAddress(x.Email); err != nil {
			return fmt.Errorf("Email must be a valid email: %w", err)
		}
	}
	if x.Kind != "" {
		switch x.Kind {
		case "a", "b", "c":
		default:
			return fmt.Errorf("Kind must be one of: a|b|c")
		}
	}
	return nil
}

// Clone returns a shallow copy of x, with slices and maps duplicated so the
// clone does not share backing storage with the original.
func (x *Point) Clone() *Point {
	if x == nil {
		return nil
	}
	c := *x
	if x.Tags != nil {
		c.Tags = append([]string(nil), x.Tags...)
	}
	return &c
}

// String returns a readable representation of x.
func (x *Point) String() string {
	if x == nil {
		return "Point(nil)"
	}
	var b strings.Builder
	b.WriteString("Point{")
	b.WriteString("X: ")
	fmt.Fprintf(&b, "%v", x.X)
	b.WriteString(", ")
	b.WriteString("Y: ")
	fmt.Fprintf(&b, "%v", x.Y)
	b.WriteString(", ")
	b.WriteString("Name: ")
	fmt.Fprintf(&b, "%q", x.Name)
	b.WriteString(", ")
	b.WriteString("Email: ")
	fmt.Fprintf(&b, "%q", x.Email)
	b.WriteString(", ")
	b.WriteString("Kind: ")
	fmt.Fprintf(&b, "%q", x.Kind)
	b.WriteString(", ")
	b.WriteString("ID: ")
	fmt.Fprintf(&b, "%v", x.ID)
	b.WriteString(", ")
	b.WriteString("Tags: ")
	fmt.Fprintf(&b, "%v", x.Tags)
	b.WriteString(", ")
	b.WriteString("secret: ")
	fmt.Fprintf(&b, "%v", x.secret)
	b.WriteString(", ")
	b.WriteString("Ignore: ")
	fmt.Fprintf(&b, "%v", x.Ignore)
	b.WriteString("}")
	return b.String()
}
